### ISSUE TITLE
The apt directory for Debian installs is gone

### ISSUE THREAD

**Issue by vonHabsi** [phusion/passenger_library#25]
The apt directory for Debian installs is gone, although the documentation refers to it., ie https://oss-binaries.phusionpassenger.com/

**Comment by FooBarWidget** [comment]
The apt directory is not gone. It's there; there is just no file index.

**Comment by vonHabsi** [comment]
When I click on https://oss-binaries.phusionpassenger.com/apt/passenger I get a "Not found" page. Is there a direct link to it which is not in the index? apt-get fails every time. Is that the correct URL for it?

**Comment by FooBarWidget** [comment]
That is the correct URL. It just has no index file.

**Comment by vonHabsi** [comment]
If the instructions for installing from apt-get are correct I will try to reinstaling from apt and send you a trace from the apt command if there are errors.
