### ISSUE TITLE
Walkthrough deployment instructions for Meteor should limit Node.js version to 0.10.x

### ISSUE THREAD

**Issue by OnixGH** [phusion/passenger_library#27]
As of the time of filing, the max version supported by Meteor is the Node.js 0.10.x line.

See also: https://www.phusionpassenger.com/library/walkthroughs/deploy/meteor/ownserver/nginx/oss/install_language_runtime.html

**Comment by OnixGH** [comment]
Fixed in https://github.com/phusion/passenger_library/commit/1d3dea22bbfd356cde52d487504fce68adb3cbbd

**Comment by yudhaprama** [comment]
No

https://deb.nodesource.com/setup_0.10 === https://deb.nodesource.com/setup

Both install latest `0.10` which is `0.10.40`

**Comment by OnixGH** [comment]
The point is that Meteor requires 0.10.x (rather than 0.12 in the old instructions). This is fixed in the mentioned commit.

**Comment by yudhaprama** [comment]
Still. It won't solve the issue. Have ETA when you support 0.10.40?

**Comment by OnixGH** [comment]
I think you are in the wrong place. Meteor support for Node.js versions has nothing to do with Passenger. See: https://github.com/meteor/meteor/issues/5124

**Comment by yudhaprama** [comment]
The MDG guy said that the Node update will come at Meteor 1.4. That's mean next year.

Thanks for letting me know
