### ISSUE TITLE
possibly old repository in deployment tutorial

### ISSUE THREAD

**Issue by jimbo-on-ruby** [phusion/passenger_library#44]
I ran into an issue while installing the nginx passenger module.

As it turns out the problem was the repository in this tutorial:

https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/nginx/oss/trusty/install_passenger.html

after I changed my passenger.list content to 

    deb https://packagecloud.io/phusion/passenger/ubuntu/ vivid main
    deb-src https://packagecloud.io/phusion/passenger/ubuntu/ vivid main

everything worked fine.

**Comment by OnixGH** [comment]
We don't officially support Ubuntu 15.04 "vivid", which is why you can't pick it in that tutorial. The packagecloud repo isn't our repo, so we can't link it from the official tutorial.

**Comment by OnixGH** [comment]
P.S. support for 15.04 was dropped due to it being end of life:
https://blog.phusion.nl/2016/02/18/passenger-5-0-25/
