### ISSUE TITLE
Redirect all requests to SSL

### ISSUE THREAD

**Issue by johanstenberg92** [phusion/passenger_library#5]
Hi,

This is quite a common request, but I can't find it anywhere in the documentation for Passenger Standalone.

Thanks for a great piece of software!!

Cheers,

Johan

**Comment by FooBarWidget** [comment]
Passenger doesn't have a mechanism to handle this. It is recommended that you do this either from the app level (e.g. with Rails's force_ssl configuration), or from the web server level (e.g. with a rewrite directive in Nginx).
