### ISSUE TITLE
Passenger and Nginx

### ISSUE THREAD

**Issue by net1957** [phusion/passenger_library#76]
it would be nice to give a little advice in the deploy page (deploy_to_production/installations/oss/ownserver/ruby/nginx/):

install nginx with `sudo apt-get install nginx` !!!

I did have a hard time to found what was missing. The title "Installing Passenger + nginx" is a little misleading...

Hope this will help other people !!

Thanks for your time on this software.

**Comment by scarhand** [comment]
For which distro and version where you following the instructions? We have different instructions for the different distributions and versions, and it would be very helpful to know with which distro/version you ran into trouble.

Thanks for the feedback!

**Comment by net1957** [comment]
it is Debian 9

**Comment by scarhand** [comment]
Yes, you are absolutely correct. The comment in the code block is a bit misleading. The text above the code block hints that you should first install Nginx, but I can see how it can easily be missed.

We'll look into it, and see if we can find a way to make it more clear that you should first install Nginx, before proceeding with the instructions in the code block.

cc: @CamJN and @lhafkamp

**Comment by lhafkamp** [comment]
We added your suggestion to the docs and made it more noticeable. Thank you for your feedback!
