### ISSUE TITLE
Passenger standalone log file not logging HTTP requests and originating IPs?

### ISSUE THREAD

**Issue by jjgh** [phusion/passenger_library#8]
Hi, I'm using Passenger standalone as described in https://github.com/phusion/passenger_library/issues/7#issuecomment-145484177 

I can't find a way to make Passenger log HTTP requests and IPs.

Since I'm not using any Ruby framework, I don't have an application level logger.
Obviously I could build it myself, but I was wondering, since Passenger standalone uses nginx behind the scenes, isn't there a place where it logs connections?
Ty.

**Comment by FooBarWidget** [comment]
Passenger outsources this kind of logging to Nginx (or Apache, if you use that). Nginx logs requests and IPs to its access log.

Passenger Standalone also uses Nginx, but we do not configure it to log requests and IPs. You could do it however with a [custom Nginx config template](https://www.phusionpassenger.com/library/config/standalone/intro.html#nginx-configuration-template). Just set the [access_log](http://nginx.org/en/docs/http/ngx_http_log_module.html) option in there.

**Comment by jjgh** [comment]
Thanks a lot for clarifying! :+1:
