### ISSUE TITLE
Documentation for installation on Ubuntu 16.04 misses step to get key

### ISSUE THREAD

**Issue by fwolfst** [phusion/passenger_library#89]
Following the instructions on https://www.phusionpassenger.com/library/install/apache/install/oss/xenial/ will lead to

```
$ sudo apt-get update
# ...
W: GPG error: https://oss-binaries.phusionpassenger.com/apt/passenger xenial Release: The following signatures couldn't be verified be
cause the public key is not available: NO_PUBKEY 561F9B9CAC40B2F7
W: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger xenial Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
# ...
```

The `sudo apt-get install -y libapache2-mod-passenger` command will fail too.

The step missing is to pull and trust the relevant key:
'sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 561F9B9CAC40B2F7`

**Comment by fwolfst** [comment]
Unfortunately documentation is not so straight forward to edit and propose a PR in 2 minutes for me, but the relevant code seems to be at https://github.com/phusion/passenger_library/blob/0ba0da66c49644fec6d82a1a0403b19c4e6bd0ec/source/install/install/shared/_debian.html.erb#L101 .

**Comment by CamJN** [comment]
New docs are here: https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/ownserver/ruby/apache/
